<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'VGS_Client' => $vendorDir . '/schibsted/sdk-php/src/Client.php',
    'VGS_Client_Exception' => $vendorDir . '/schibsted/sdk-php/src/Client/Exception.php',
);
